version: "3"

services:
  api:
    volumes: 
      - .:/go/src/github.com/minhajuddinkhan/muntaha
    container_name: muntaha
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./env/development
    ports:
      - 8080:8080
  neo4j:
    volumes:
      - /var/lib/neo4j/data:/var/lib/neo4j/data
    container_name: muntaha_neo4j
    image: neo4j:3.5.3
    env_file:
      - ./env/development
    ports:
      - 7474:7474 
      - 7687:7687
